config/routes.rb
Rails.application.routes.draw do
	root to: "welcome#show"

	resources :recipes
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/meal.rb
class Meal < ApplicationRecord
	belongs_to :meal_plan
	belongs_to :recipe
end

app/models/meal_plan.rb
class MealPlan < ApplicationRecord
	belongs_to :user
	has_many :meals

	validates :start_date, presence: true
	validates :end_date, presence: true
	validates :user, presence: true

	def build_meals
		user_recipe_ids = user.recipes.pluck(:id)
		(start_date..end_date).each do |date|
			unused_recipe_ids = user_recipe_ids - meals.map(&:recipe_id)
			if unused_recipe_ids.empty?
				availabel_recipe_ids = user_recipe_ids
			else
				availabel_recipe_ids = unused_recipe_ids
			end
			meals.build(date: date, recipe_id: availabel_recipe_ids.sample)
		end
	end
end

app/models/recipe.rb
class Recipe < ApplicationRecord
	belongs_to  :user

	validates :user, presence: true
	validates :name, presence: true, uniqueness: { scope: :user_id }
	validates :description, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  include Clearance::User

  has_many :recipes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Clearance::Controller
  protect_from_forgery with: :exception
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
	before_action :require_login

	def index
		@recipes = current_user.recipes.order(:id)
	end

	def show 
		@recipe = current_user.recipes.find(params[:id])
	end

	def new
		@recipe = current_user.recipes.build
	end

	def create
		@recipe = current_user.recipes.build(recipe_params)

		if @recipe.save
			redirect_to recipe_path(@recipe), notice: "Recipe Created!"
		else
			@errors = @recipe.errors.full_messages
			render :new
		end
	end

	def edit
		@recipe = current_user.recipes.find(params[:id])
	end

	def update
		@recipe = current_user.recipes.find(params[:id])

		if @recipe.update_attributes(recipe_params)
			redirect_to recipe_path(@recipe), notice: "Recipe Uploaded!"
		else
			@errors = @recipe.errors.full_messages
			render :edit
		end
	end
	def destroy
		recipe = current_user.recipes.find(params[:id])
		recipe.destroy
		redirect_to recipes_path, notice: "Delete Recipe: #{recipe.name}"
	end
	private
		def recipe_params
			params.require(:recipe).permit(:name, :description)
		end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	def show

	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MealPlan</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
  	<header>
  		<% if signed_in? %>
  			Signed in as: <%= current_user.email %>
  			<%= button_to 'Sign out', sign_out_path, method: :delete %>
  		<% else %>
  			<%= link_to 'Sign in', sign_in_path %>
  		<% end %>
  	</header>
  	<section>
  		<div id="flash">
  			<% flash.each do |key, value| %>
  			<div class="flash <%= key %>"><%= value %></div>
  			<% end %>
  		</div>

  		<%= yield %>    	
  	</section>
  </body>
</html>

app/views/recipes/_form.html.erb
<% if @errors.present? %>
	<div class="errors">
		<ul>
			<% @errors.each do |error| %>
				<li><%= error %></li>
			<% end %>
		</ul>
	</div>
<% end %>

<%= form_for @recipe do |form| %>
	<div class="form-group">
		<%= form.label :name %>
		<%= form.text_field :name %>
	</div>
	<div class="form-group">
		<%= form.label :description %>
		<%= form.text_area :description %>
	</div>
	<div class="actions">
		<%= form.submit %>
	</div>
<% end %>

app/views/recipes/edit.html.erb
<h1>Edit Recipe</h1>

<%= render partial: "form" %>

app/views/recipes/index.html.erb
<h1>Recipes</h1>
<div><%= link_to "New Recipe", new_recipe_path %></div>
<div class="recipes">
	<% @recipes.each do |recipe| %>
		<div class="recipe">
			<h3><%= link_to recipe.name, recipe_path(recipe) %></h3>
			<p><%= recipe.description %></p>
			<ul class="recipe-actions">
				<li><%= link_to "Edit", edit_recipe_path(recipe) %></li>
				<li><%= link_to "Delete", recipe_path(recipe), data: { confirm: "are you sure you want to delete: #{recipe.name}?", }, method: :delete %></li>
			</ul>
		</div>
	<% end %>
</div>

app/views/recipes/new.html.erb
<h1>New Recipe</h1>

<%= render partial: "form" %>

app/views/recipes/show.html.erb
<h1><%= @recipe.name %></h1>
<h2>Description:</h2>
<p><%= @recipe.description %></p>

<div>
	<ul class="recipe-actions">
		<li><%= link_to "Back", recipes_path %></li>
		<li><%= link_to "Edit", edit_recipe_path(@recipe) %></li>
		<li><%= link_to "Delete", recipe_path(@recipe), data: { confirm: "are you sure you want to delete: #{@recipe.name}?", }, method: :delete %></li>
	</ul>
</div>

app/views/welcome/show.html.erb
<h1>Welcome</h1>